# Generated by Django 2.0.2 on 2019-07-26 15:25

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('11', '11'), ('7', '7'), ('5', '5')], max_length=50)),
                ('servicios', multiselectfield.db.fields.MultiSelectField(choices=[('vs', 'Vestuario'), ('il', 'Iluminacion'), ('ce', 'Cesped Sintetico')], max_length=8)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
